/*
    Copyright 2019 Samsung SDS
    
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    
        http://www.apache.org/licenses/LICENSE-2.0
    
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.samsung.sds.brightics.common.network.proto;

public interface ClientReadyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.samsung.sds.brightics.common.network.proto.ClientReadyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientId = 1;</code>
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string clientHost = 2;</code>
   */
  java.lang.String getClientHost();
  /**
   * <code>string clientHost = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientHostBytes();

  /**
   * <code>int32 clientPort = 3;</code>
   */
  int getClientPort();

  /**
   * <code>string core = 4;</code>
   */
  java.lang.String getCore();
  /**
   * <code>string core = 4;</code>
   */
  com.google.protobuf.ByteString
      getCoreBytes();

  /**
   * <code>string memory = 5;</code>
   */
  java.lang.String getMemory();
  /**
   * <code>string memory = 5;</code>
   */
  com.google.protobuf.ByteString
      getMemoryBytes();

  /**
   * <code>.com.samsung.sds.brightics.common.network.proto.ClientReadyMessage.ClientType clientType = 6;</code>
   */
  int getClientTypeValue();
  /**
   * <code>.com.samsung.sds.brightics.common.network.proto.ClientReadyMessage.ClientType clientType = 6;</code>
   */
  com.samsung.sds.brightics.common.network.proto.ClientReadyMessage.ClientType getClientType();
}
