# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import calcitepython_pb2 as calcitepython__pb2


class CalcitePythonServiceStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.setSchemaModel = channel.unary_unary(
                '/calcitePandas.CalcitePythonService/setSchemaModel',
                request_serializer=calcitepython__pb2.IncomingMsg.SerializeToString,
                response_deserializer=calcitepython__pb2.ReplyMsg.FromString,
                )
        self.parseSql = channel.unary_unary(
                '/calcitePandas.CalcitePythonService/parseSql',
                request_serializer=calcitepython__pb2.IncomingMsg.SerializeToString,
                response_deserializer=calcitepython__pb2.ReplyMsg.FromString,
                )


class CalcitePythonServiceServicer(object):
    """Interface exported by the server.
    """

    def setSchemaModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def parseSql(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalcitePythonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'setSchemaModel': grpc.unary_unary_rpc_method_handler(
                    servicer.setSchemaModel,
                    request_deserializer=calcitepython__pb2.IncomingMsg.FromString,
                    response_serializer=calcitepython__pb2.ReplyMsg.SerializeToString,
            ),
            'parseSql': grpc.unary_unary_rpc_method_handler(
                    servicer.parseSql,
                    request_deserializer=calcitepython__pb2.IncomingMsg.FromString,
                    response_serializer=calcitepython__pb2.ReplyMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calcitePandas.CalcitePythonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalcitePythonService(object):
    """Interface exported by the server.
    """

    @staticmethod
    def setSchemaModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calcitePandas.CalcitePythonService/setSchemaModel',
            calcitepython__pb2.IncomingMsg.SerializeToString,
            calcitepython__pb2.ReplyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def parseSql(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calcitePandas.CalcitePythonService/parseSql',
            calcitepython__pb2.IncomingMsg.SerializeToString,
            calcitepython__pb2.ReplyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
