// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package com.samsung.sds.brightics.common.network.proto.metadata;

public interface AliasMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alias = 1;</code>
   */
  java.lang.String getAlias();
  /**
   * <code>string alias = 1;</code>
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <code>string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
