// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package com.samsung.sds.brightics.common.network.proto.metadata;

public interface DataKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.samsung.sds.brightics.common.network.proto.metadata.DataKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mid = 1;</code>
   */
  java.lang.String getMid();
  /**
   * <code>string mid = 1;</code>
   */
  com.google.protobuf.ByteString
      getMidBytes();

  /**
   * <code>string tid = 2;</code>
   */
  java.lang.String getTid();
  /**
   * <code>string tid = 2;</code>
   */
  com.google.protobuf.ByteString
      getTidBytes();
}
