// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package com.samsung.sds.brightics.common.network.proto.metadata;

/**
 * Protobuf type {@code com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage}
 */
public  final class DataPermissionMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage)
    DataPermissionMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataPermissionMessage.newBuilder() to construct.
  private DataPermissionMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataPermissionMessage() {
    user_ = "";
    target_ = java.util.Collections.emptyList();
    permission_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DataPermissionMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            user_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              target_ = new java.util.ArrayList<com.samsung.sds.brightics.common.network.proto.metadata.DataKey>();
              mutable_bitField0_ |= 0x00000002;
            }
            target_.add(
                input.readMessage(com.samsung.sds.brightics.common.network.proto.metadata.DataKey.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            permission_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        target_ = java.util.Collections.unmodifiableList(target_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.samsung.sds.brightics.common.network.proto.metadata.MetaDataProto.internal_static_com_samsung_sds_brightics_common_network_proto_metadata_DataPermissionMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.samsung.sds.brightics.common.network.proto.metadata.MetaDataProto.internal_static_com_samsung_sds_brightics_common_network_proto_metadata_DataPermissionMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage.class, com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage.Builder.class);
  }

  private int bitField0_;
  public static final int USER_FIELD_NUMBER = 1;
  private volatile java.lang.Object user_;
  /**
   * <code>string user = 1;</code>
   */
  public java.lang.String getUser() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      user_ = s;
      return s;
    }
  }
  /**
   * <code>string user = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserBytes() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      user_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_FIELD_NUMBER = 2;
  private java.util.List<com.samsung.sds.brightics.common.network.proto.metadata.DataKey> target_;
  /**
   * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
   */
  public java.util.List<com.samsung.sds.brightics.common.network.proto.metadata.DataKey> getTargetList() {
    return target_;
  }
  /**
   * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
   */
  public java.util.List<? extends com.samsung.sds.brightics.common.network.proto.metadata.DataKeyOrBuilder> 
      getTargetOrBuilderList() {
    return target_;
  }
  /**
   * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
   */
  public int getTargetCount() {
    return target_.size();
  }
  /**
   * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
   */
  public com.samsung.sds.brightics.common.network.proto.metadata.DataKey getTarget(int index) {
    return target_.get(index);
  }
  /**
   * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
   */
  public com.samsung.sds.brightics.common.network.proto.metadata.DataKeyOrBuilder getTargetOrBuilder(
      int index) {
    return target_.get(index);
  }

  public static final int PERMISSION_FIELD_NUMBER = 3;
  private volatile java.lang.Object permission_;
  /**
   * <code>string permission = 3;</code>
   */
  public java.lang.String getPermission() {
    java.lang.Object ref = permission_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      permission_ = s;
      return s;
    }
  }
  /**
   * <code>string permission = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPermissionBytes() {
    java.lang.Object ref = permission_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      permission_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, user_);
    }
    for (int i = 0; i < target_.size(); i++) {
      output.writeMessage(2, target_.get(i));
    }
    if (!getPermissionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, permission_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, user_);
    }
    for (int i = 0; i < target_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, target_.get(i));
    }
    if (!getPermissionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, permission_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage)) {
      return super.equals(obj);
    }
    com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage other = (com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage) obj;

    boolean result = true;
    result = result && getUser()
        .equals(other.getUser());
    result = result && getTargetList()
        .equals(other.getTargetList());
    result = result && getPermission()
        .equals(other.getPermission());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_FIELD_NUMBER;
    hash = (53 * hash) + getUser().hashCode();
    if (getTargetCount() > 0) {
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTargetList().hashCode();
    }
    hash = (37 * hash) + PERMISSION_FIELD_NUMBER;
    hash = (53 * hash) + getPermission().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage)
      com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.samsung.sds.brightics.common.network.proto.metadata.MetaDataProto.internal_static_com_samsung_sds_brightics_common_network_proto_metadata_DataPermissionMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.samsung.sds.brightics.common.network.proto.metadata.MetaDataProto.internal_static_com_samsung_sds_brightics_common_network_proto_metadata_DataPermissionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage.class, com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage.Builder.class);
    }

    // Construct using com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTargetFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      user_ = "";

      if (targetBuilder_ == null) {
        target_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        targetBuilder_.clear();
      }
      permission_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.samsung.sds.brightics.common.network.proto.metadata.MetaDataProto.internal_static_com_samsung_sds_brightics_common_network_proto_metadata_DataPermissionMessage_descriptor;
    }

    public com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage getDefaultInstanceForType() {
      return com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage.getDefaultInstance();
    }

    public com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage build() {
      com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage buildPartial() {
      com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage result = new com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.user_ = user_;
      if (targetBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          target_ = java.util.Collections.unmodifiableList(target_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.target_ = target_;
      } else {
        result.target_ = targetBuilder_.build();
      }
      result.permission_ = permission_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage) {
        return mergeFrom((com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage other) {
      if (other == com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage.getDefaultInstance()) return this;
      if (!other.getUser().isEmpty()) {
        user_ = other.user_;
        onChanged();
      }
      if (targetBuilder_ == null) {
        if (!other.target_.isEmpty()) {
          if (target_.isEmpty()) {
            target_ = other.target_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTargetIsMutable();
            target_.addAll(other.target_);
          }
          onChanged();
        }
      } else {
        if (!other.target_.isEmpty()) {
          if (targetBuilder_.isEmpty()) {
            targetBuilder_.dispose();
            targetBuilder_ = null;
            target_ = other.target_;
            bitField0_ = (bitField0_ & ~0x00000002);
            targetBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTargetFieldBuilder() : null;
          } else {
            targetBuilder_.addAllMessages(other.target_);
          }
        }
      }
      if (!other.getPermission().isEmpty()) {
        permission_ = other.permission_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object user_ = "";
    /**
     * <code>string user = 1;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user = 1;</code>
     */
    public Builder setUser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      user_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user = 1;</code>
     */
    public Builder clearUser() {
      
      user_ = getDefaultInstance().getUser();
      onChanged();
      return this;
    }
    /**
     * <code>string user = 1;</code>
     */
    public Builder setUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      user_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.samsung.sds.brightics.common.network.proto.metadata.DataKey> target_ =
      java.util.Collections.emptyList();
    private void ensureTargetIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        target_ = new java.util.ArrayList<com.samsung.sds.brightics.common.network.proto.metadata.DataKey>(target_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.samsung.sds.brightics.common.network.proto.metadata.DataKey, com.samsung.sds.brightics.common.network.proto.metadata.DataKey.Builder, com.samsung.sds.brightics.common.network.proto.metadata.DataKeyOrBuilder> targetBuilder_;

    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public java.util.List<com.samsung.sds.brightics.common.network.proto.metadata.DataKey> getTargetList() {
      if (targetBuilder_ == null) {
        return java.util.Collections.unmodifiableList(target_);
      } else {
        return targetBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public int getTargetCount() {
      if (targetBuilder_ == null) {
        return target_.size();
      } else {
        return targetBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public com.samsung.sds.brightics.common.network.proto.metadata.DataKey getTarget(int index) {
      if (targetBuilder_ == null) {
        return target_.get(index);
      } else {
        return targetBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public Builder setTarget(
        int index, com.samsung.sds.brightics.common.network.proto.metadata.DataKey value) {
      if (targetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetIsMutable();
        target_.set(index, value);
        onChanged();
      } else {
        targetBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public Builder setTarget(
        int index, com.samsung.sds.brightics.common.network.proto.metadata.DataKey.Builder builderForValue) {
      if (targetBuilder_ == null) {
        ensureTargetIsMutable();
        target_.set(index, builderForValue.build());
        onChanged();
      } else {
        targetBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public Builder addTarget(com.samsung.sds.brightics.common.network.proto.metadata.DataKey value) {
      if (targetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetIsMutable();
        target_.add(value);
        onChanged();
      } else {
        targetBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public Builder addTarget(
        int index, com.samsung.sds.brightics.common.network.proto.metadata.DataKey value) {
      if (targetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetIsMutable();
        target_.add(index, value);
        onChanged();
      } else {
        targetBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public Builder addTarget(
        com.samsung.sds.brightics.common.network.proto.metadata.DataKey.Builder builderForValue) {
      if (targetBuilder_ == null) {
        ensureTargetIsMutable();
        target_.add(builderForValue.build());
        onChanged();
      } else {
        targetBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public Builder addTarget(
        int index, com.samsung.sds.brightics.common.network.proto.metadata.DataKey.Builder builderForValue) {
      if (targetBuilder_ == null) {
        ensureTargetIsMutable();
        target_.add(index, builderForValue.build());
        onChanged();
      } else {
        targetBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public Builder addAllTarget(
        java.lang.Iterable<? extends com.samsung.sds.brightics.common.network.proto.metadata.DataKey> values) {
      if (targetBuilder_ == null) {
        ensureTargetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, target_);
        onChanged();
      } else {
        targetBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public Builder clearTarget() {
      if (targetBuilder_ == null) {
        target_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        targetBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public Builder removeTarget(int index) {
      if (targetBuilder_ == null) {
        ensureTargetIsMutable();
        target_.remove(index);
        onChanged();
      } else {
        targetBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public com.samsung.sds.brightics.common.network.proto.metadata.DataKey.Builder getTargetBuilder(
        int index) {
      return getTargetFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public com.samsung.sds.brightics.common.network.proto.metadata.DataKeyOrBuilder getTargetOrBuilder(
        int index) {
      if (targetBuilder_ == null) {
        return target_.get(index);  } else {
        return targetBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public java.util.List<? extends com.samsung.sds.brightics.common.network.proto.metadata.DataKeyOrBuilder> 
         getTargetOrBuilderList() {
      if (targetBuilder_ != null) {
        return targetBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(target_);
      }
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public com.samsung.sds.brightics.common.network.proto.metadata.DataKey.Builder addTargetBuilder() {
      return getTargetFieldBuilder().addBuilder(
          com.samsung.sds.brightics.common.network.proto.metadata.DataKey.getDefaultInstance());
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public com.samsung.sds.brightics.common.network.proto.metadata.DataKey.Builder addTargetBuilder(
        int index) {
      return getTargetFieldBuilder().addBuilder(
          index, com.samsung.sds.brightics.common.network.proto.metadata.DataKey.getDefaultInstance());
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.DataKey target = 2;</code>
     */
    public java.util.List<com.samsung.sds.brightics.common.network.proto.metadata.DataKey.Builder> 
         getTargetBuilderList() {
      return getTargetFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.samsung.sds.brightics.common.network.proto.metadata.DataKey, com.samsung.sds.brightics.common.network.proto.metadata.DataKey.Builder, com.samsung.sds.brightics.common.network.proto.metadata.DataKeyOrBuilder> 
        getTargetFieldBuilder() {
      if (targetBuilder_ == null) {
        targetBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.samsung.sds.brightics.common.network.proto.metadata.DataKey, com.samsung.sds.brightics.common.network.proto.metadata.DataKey.Builder, com.samsung.sds.brightics.common.network.proto.metadata.DataKeyOrBuilder>(
                target_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        target_ = null;
      }
      return targetBuilder_;
    }

    private java.lang.Object permission_ = "";
    /**
     * <code>string permission = 3;</code>
     */
    public java.lang.String getPermission() {
      java.lang.Object ref = permission_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        permission_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string permission = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPermissionBytes() {
      java.lang.Object ref = permission_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        permission_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string permission = 3;</code>
     */
    public Builder setPermission(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      permission_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string permission = 3;</code>
     */
    public Builder clearPermission() {
      
      permission_ = getDefaultInstance().getPermission();
      onChanged();
      return this;
    }
    /**
     * <code>string permission = 3;</code>
     */
    public Builder setPermissionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      permission_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage)
  }

  // @@protoc_insertion_point(class_scope:com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage)
  private static final com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage();
  }

  public static com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataPermissionMessage>
      PARSER = new com.google.protobuf.AbstractParser<DataPermissionMessage>() {
    public DataPermissionMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DataPermissionMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DataPermissionMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataPermissionMessage> getParserForType() {
    return PARSER;
  }

  public com.samsung.sds.brightics.common.network.proto.metadata.DataPermissionMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

