// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package com.samsung.sds.brightics.common.network.proto.metadata;

public interface DataAliasByDataKeyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.samsung.sds.brightics.common.network.proto.metadata.DataAliasByDataKeyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string sourceDataKey = 2;</code>
   */
  java.lang.String getSourceDataKey();
  /**
   * <code>string sourceDataKey = 2;</code>
   */
  com.google.protobuf.ByteString
      getSourceDataKeyBytes();

  /**
   * <code>string aliasDataKey = 3;</code>
   */
  java.lang.String getAliasDataKey();
  /**
   * <code>string aliasDataKey = 3;</code>
   */
  com.google.protobuf.ByteString
      getAliasDataKeyBytes();
}
