// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package com.samsung.sds.brightics.common.network.proto.metadata;

/**
 * Protobuf enum {@code com.samsung.sds.brightics.common.network.proto.metadata.DataStatusType}
 */
public enum DataStatusType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ALL = 0;</code>
   */
  ALL(0),
  /**
   * <code>UPLOAD = 1;</code>
   */
  UPLOAD(1),
  /**
   * <code>TABLE = 2;</code>
   */
  TABLE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ALL = 0;</code>
   */
  public static final int ALL_VALUE = 0;
  /**
   * <code>UPLOAD = 1;</code>
   */
  public static final int UPLOAD_VALUE = 1;
  /**
   * <code>TABLE = 2;</code>
   */
  public static final int TABLE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DataStatusType valueOf(int value) {
    return forNumber(value);
  }

  public static DataStatusType forNumber(int value) {
    switch (value) {
      case 0: return ALL;
      case 1: return UPLOAD;
      case 2: return TABLE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DataStatusType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DataStatusType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DataStatusType>() {
          public DataStatusType findValueByNumber(int number) {
            return DataStatusType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.samsung.sds.brightics.common.network.proto.metadata.MetaDataProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final DataStatusType[] VALUES = values();

  public static DataStatusType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DataStatusType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.samsung.sds.brightics.common.network.proto.metadata.DataStatusType)
}

