// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package com.samsung.sds.brightics.common.network.proto.metadata;

/**
 * Protobuf type {@code com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage}
 */
public  final class ExecuteSqlMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage)
    ExecuteSqlMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecuteSqlMessage.newBuilder() to construct.
  private ExecuteSqlMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteSqlMessage() {
    user_ = "";
    alias_ = java.util.Collections.emptyList();
    limit_ = "";
    sql_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExecuteSqlMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            user_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              alias_ = new java.util.ArrayList<com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage>();
              mutable_bitField0_ |= 0x00000002;
            }
            alias_.add(
                input.readMessage(com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            limit_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            sql_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        alias_ = java.util.Collections.unmodifiableList(alias_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.samsung.sds.brightics.common.network.proto.metadata.MetaDataProto.internal_static_com_samsung_sds_brightics_common_network_proto_metadata_ExecuteSqlMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.samsung.sds.brightics.common.network.proto.metadata.MetaDataProto.internal_static_com_samsung_sds_brightics_common_network_proto_metadata_ExecuteSqlMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage.class, com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage.Builder.class);
  }

  private int bitField0_;
  public static final int USER_FIELD_NUMBER = 1;
  private volatile java.lang.Object user_;
  /**
   * <code>string user = 1;</code>
   */
  public java.lang.String getUser() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      user_ = s;
      return s;
    }
  }
  /**
   * <code>string user = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserBytes() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      user_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALIAS_FIELD_NUMBER = 2;
  private java.util.List<com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage> alias_;
  /**
   * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
   */
  public java.util.List<com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage> getAliasList() {
    return alias_;
  }
  /**
   * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
   */
  public java.util.List<? extends com.samsung.sds.brightics.common.network.proto.metadata.AliasMessageOrBuilder> 
      getAliasOrBuilderList() {
    return alias_;
  }
  /**
   * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
   */
  public int getAliasCount() {
    return alias_.size();
  }
  /**
   * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
   */
  public com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage getAlias(int index) {
    return alias_.get(index);
  }
  /**
   * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
   */
  public com.samsung.sds.brightics.common.network.proto.metadata.AliasMessageOrBuilder getAliasOrBuilder(
      int index) {
    return alias_.get(index);
  }

  public static final int LIMIT_FIELD_NUMBER = 3;
  private volatile java.lang.Object limit_;
  /**
   * <code>string limit = 3;</code>
   */
  public java.lang.String getLimit() {
    java.lang.Object ref = limit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      limit_ = s;
      return s;
    }
  }
  /**
   * <code>string limit = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLimitBytes() {
    java.lang.Object ref = limit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      limit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SQL_FIELD_NUMBER = 4;
  private volatile java.lang.Object sql_;
  /**
   * <code>string sql = 4;</code>
   */
  public java.lang.String getSql() {
    java.lang.Object ref = sql_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sql_ = s;
      return s;
    }
  }
  /**
   * <code>string sql = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSqlBytes() {
    java.lang.Object ref = sql_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sql_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, user_);
    }
    for (int i = 0; i < alias_.size(); i++) {
      output.writeMessage(2, alias_.get(i));
    }
    if (!getLimitBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, limit_);
    }
    if (!getSqlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sql_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, user_);
    }
    for (int i = 0; i < alias_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, alias_.get(i));
    }
    if (!getLimitBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, limit_);
    }
    if (!getSqlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sql_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage)) {
      return super.equals(obj);
    }
    com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage other = (com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage) obj;

    boolean result = true;
    result = result && getUser()
        .equals(other.getUser());
    result = result && getAliasList()
        .equals(other.getAliasList());
    result = result && getLimit()
        .equals(other.getLimit());
    result = result && getSql()
        .equals(other.getSql());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_FIELD_NUMBER;
    hash = (53 * hash) + getUser().hashCode();
    if (getAliasCount() > 0) {
      hash = (37 * hash) + ALIAS_FIELD_NUMBER;
      hash = (53 * hash) + getAliasList().hashCode();
    }
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLimit().hashCode();
    hash = (37 * hash) + SQL_FIELD_NUMBER;
    hash = (53 * hash) + getSql().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage)
      com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.samsung.sds.brightics.common.network.proto.metadata.MetaDataProto.internal_static_com_samsung_sds_brightics_common_network_proto_metadata_ExecuteSqlMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.samsung.sds.brightics.common.network.proto.metadata.MetaDataProto.internal_static_com_samsung_sds_brightics_common_network_proto_metadata_ExecuteSqlMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage.class, com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage.Builder.class);
    }

    // Construct using com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAliasFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      user_ = "";

      if (aliasBuilder_ == null) {
        alias_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        aliasBuilder_.clear();
      }
      limit_ = "";

      sql_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.samsung.sds.brightics.common.network.proto.metadata.MetaDataProto.internal_static_com_samsung_sds_brightics_common_network_proto_metadata_ExecuteSqlMessage_descriptor;
    }

    public com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage getDefaultInstanceForType() {
      return com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage.getDefaultInstance();
    }

    public com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage build() {
      com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage buildPartial() {
      com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage result = new com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.user_ = user_;
      if (aliasBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          alias_ = java.util.Collections.unmodifiableList(alias_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.alias_ = alias_;
      } else {
        result.alias_ = aliasBuilder_.build();
      }
      result.limit_ = limit_;
      result.sql_ = sql_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage) {
        return mergeFrom((com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage other) {
      if (other == com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage.getDefaultInstance()) return this;
      if (!other.getUser().isEmpty()) {
        user_ = other.user_;
        onChanged();
      }
      if (aliasBuilder_ == null) {
        if (!other.alias_.isEmpty()) {
          if (alias_.isEmpty()) {
            alias_ = other.alias_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAliasIsMutable();
            alias_.addAll(other.alias_);
          }
          onChanged();
        }
      } else {
        if (!other.alias_.isEmpty()) {
          if (aliasBuilder_.isEmpty()) {
            aliasBuilder_.dispose();
            aliasBuilder_ = null;
            alias_ = other.alias_;
            bitField0_ = (bitField0_ & ~0x00000002);
            aliasBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAliasFieldBuilder() : null;
          } else {
            aliasBuilder_.addAllMessages(other.alias_);
          }
        }
      }
      if (!other.getLimit().isEmpty()) {
        limit_ = other.limit_;
        onChanged();
      }
      if (!other.getSql().isEmpty()) {
        sql_ = other.sql_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object user_ = "";
    /**
     * <code>string user = 1;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user = 1;</code>
     */
    public Builder setUser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      user_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user = 1;</code>
     */
    public Builder clearUser() {
      
      user_ = getDefaultInstance().getUser();
      onChanged();
      return this;
    }
    /**
     * <code>string user = 1;</code>
     */
    public Builder setUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      user_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage> alias_ =
      java.util.Collections.emptyList();
    private void ensureAliasIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        alias_ = new java.util.ArrayList<com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage>(alias_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage, com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.Builder, com.samsung.sds.brightics.common.network.proto.metadata.AliasMessageOrBuilder> aliasBuilder_;

    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public java.util.List<com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage> getAliasList() {
      if (aliasBuilder_ == null) {
        return java.util.Collections.unmodifiableList(alias_);
      } else {
        return aliasBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public int getAliasCount() {
      if (aliasBuilder_ == null) {
        return alias_.size();
      } else {
        return aliasBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage getAlias(int index) {
      if (aliasBuilder_ == null) {
        return alias_.get(index);
      } else {
        return aliasBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public Builder setAlias(
        int index, com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage value) {
      if (aliasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAliasIsMutable();
        alias_.set(index, value);
        onChanged();
      } else {
        aliasBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public Builder setAlias(
        int index, com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.Builder builderForValue) {
      if (aliasBuilder_ == null) {
        ensureAliasIsMutable();
        alias_.set(index, builderForValue.build());
        onChanged();
      } else {
        aliasBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public Builder addAlias(com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage value) {
      if (aliasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAliasIsMutable();
        alias_.add(value);
        onChanged();
      } else {
        aliasBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public Builder addAlias(
        int index, com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage value) {
      if (aliasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAliasIsMutable();
        alias_.add(index, value);
        onChanged();
      } else {
        aliasBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public Builder addAlias(
        com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.Builder builderForValue) {
      if (aliasBuilder_ == null) {
        ensureAliasIsMutable();
        alias_.add(builderForValue.build());
        onChanged();
      } else {
        aliasBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public Builder addAlias(
        int index, com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.Builder builderForValue) {
      if (aliasBuilder_ == null) {
        ensureAliasIsMutable();
        alias_.add(index, builderForValue.build());
        onChanged();
      } else {
        aliasBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public Builder addAllAlias(
        java.lang.Iterable<? extends com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage> values) {
      if (aliasBuilder_ == null) {
        ensureAliasIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, alias_);
        onChanged();
      } else {
        aliasBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public Builder clearAlias() {
      if (aliasBuilder_ == null) {
        alias_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        aliasBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public Builder removeAlias(int index) {
      if (aliasBuilder_ == null) {
        ensureAliasIsMutable();
        alias_.remove(index);
        onChanged();
      } else {
        aliasBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.Builder getAliasBuilder(
        int index) {
      return getAliasFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public com.samsung.sds.brightics.common.network.proto.metadata.AliasMessageOrBuilder getAliasOrBuilder(
        int index) {
      if (aliasBuilder_ == null) {
        return alias_.get(index);  } else {
        return aliasBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public java.util.List<? extends com.samsung.sds.brightics.common.network.proto.metadata.AliasMessageOrBuilder> 
         getAliasOrBuilderList() {
      if (aliasBuilder_ != null) {
        return aliasBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(alias_);
      }
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.Builder addAliasBuilder() {
      return getAliasFieldBuilder().addBuilder(
          com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.Builder addAliasBuilder(
        int index) {
      return getAliasFieldBuilder().addBuilder(
          index, com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage alias = 2;</code>
     */
    public java.util.List<com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.Builder> 
         getAliasBuilderList() {
      return getAliasFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage, com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.Builder, com.samsung.sds.brightics.common.network.proto.metadata.AliasMessageOrBuilder> 
        getAliasFieldBuilder() {
      if (aliasBuilder_ == null) {
        aliasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage, com.samsung.sds.brightics.common.network.proto.metadata.AliasMessage.Builder, com.samsung.sds.brightics.common.network.proto.metadata.AliasMessageOrBuilder>(
                alias_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        alias_ = null;
      }
      return aliasBuilder_;
    }

    private java.lang.Object limit_ = "";
    /**
     * <code>string limit = 3;</code>
     */
    public java.lang.String getLimit() {
      java.lang.Object ref = limit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        limit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string limit = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLimitBytes() {
      java.lang.Object ref = limit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        limit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string limit = 3;</code>
     */
    public Builder setLimit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      limit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string limit = 3;</code>
     */
    public Builder clearLimit() {
      
      limit_ = getDefaultInstance().getLimit();
      onChanged();
      return this;
    }
    /**
     * <code>string limit = 3;</code>
     */
    public Builder setLimitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      limit_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sql_ = "";
    /**
     * <code>string sql = 4;</code>
     */
    public java.lang.String getSql() {
      java.lang.Object ref = sql_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sql_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sql = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSqlBytes() {
      java.lang.Object ref = sql_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sql_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sql = 4;</code>
     */
    public Builder setSql(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sql_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sql = 4;</code>
     */
    public Builder clearSql() {
      
      sql_ = getDefaultInstance().getSql();
      onChanged();
      return this;
    }
    /**
     * <code>string sql = 4;</code>
     */
    public Builder setSqlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sql_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage)
  }

  // @@protoc_insertion_point(class_scope:com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage)
  private static final com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage();
  }

  public static com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteSqlMessage>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteSqlMessage>() {
    public ExecuteSqlMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExecuteSqlMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExecuteSqlMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteSqlMessage> getParserForType() {
    return PARSER;
  }

  public com.samsung.sds.brightics.common.network.proto.metadata.ExecuteSqlMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

