// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package com.samsung.sds.brightics.common.network.proto.task;

public interface StopTaskMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.samsung.sds.brightics.common.network.proto.task.StopTaskMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string targetTaskId = 1;</code>
   */
  java.lang.String getTargetTaskId();
  /**
   * <code>string targetTaskId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTargetTaskIdBytes();

  /**
   * <code>string user = 2;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string context = 4;</code>
   */
  java.lang.String getContext();
  /**
   * <code>string context = 4;</code>
   */
  com.google.protobuf.ByteString
      getContextBytes();
}
