// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: database.proto

package com.samsung.sds.brightics.common.network.proto.database;

public interface ConnectionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.samsung.sds.brightics.common.network.proto.database.ConnectionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string user = 2;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string driver = 4;</code>
   */
  java.lang.String getDriver();
  /**
   * <code>string driver = 4;</code>
   */
  com.google.protobuf.ByteString
      getDriverBytes();
}
