// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: database.proto

package com.samsung.sds.brightics.common.network.proto.database;

public interface ResultDBMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.samsung.sds.brightics.common.network.proto.database.ResultDBMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string detailMessage = 3;</code>
   */
  java.lang.String getDetailMessage();
  /**
   * <code>string detailMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getDetailMessageBytes();

  /**
   * <code>.com.samsung.sds.brightics.common.network.proto.MessageStatus messageStatus = 4;</code>
   */
  int getMessageStatusValue();
  /**
   * <code>.com.samsung.sds.brightics.common.network.proto.MessageStatus messageStatus = 4;</code>
   */
  com.samsung.sds.brightics.common.network.proto.MessageStatus getMessageStatus();
}
