// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package com.samsung.sds.brightics.common.network.proto.stream;

public interface ReadMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.samsung.sds.brightics.common.network.proto.stream.ReadMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string delimiter = 3;</code>
   */
  java.lang.String getDelimiter();
  /**
   * <code>string delimiter = 3;</code>
   */
  com.google.protobuf.ByteString
      getDelimiterBytes();
}
