/*
    Copyright 2019 Samsung SDS
    
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    
        http://www.apache.org/licenses/LICENSE-2.0
    
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package com.samsung.sds.brightics.common.network.proto.stream;

public interface ReadMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.samsung.sds.brightics.common.network.proto.stream.ReadMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string delimiter = 3;</code>
   */
  java.lang.String getDelimiter();
  /**
   * <code>string delimiter = 3;</code>
   */
  com.google.protobuf.ByteString
      getDelimiterBytes();

  /**
   * <code>string tempKey = 4;</code>
   */
  java.lang.String getTempKey();
  /**
   * <code>string tempKey = 4;</code>
   */
  com.google.protobuf.ByteString
      getTempKeyBytes();
}
