// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package com.samsung.sds.brightics.common.network.proto.stream;

public interface WriteMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.samsung.sds.brightics.common.network.proto.stream.WriteMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string path = 2;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 2;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>string tempKey = 3;</code>
   */
  java.lang.String getTempKey();
  /**
   * <code>string tempKey = 3;</code>
   */
  com.google.protobuf.ByteString
      getTempKeyBytes();

  /**
   * <code>string parameters = 4;</code>
   */
  java.lang.String getParameters();
  /**
   * <code>string parameters = 4;</code>
   */
  com.google.protobuf.ByteString
      getParametersBytes();

  /**
   * <code>string errorMessage = 5;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 5;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
